In [ ]:
!pip install tensorflow pandas numpy scikit-learn joblib

Requirement already satisfied: tensorflow in /usr/local/lib/python3.13/dist-packages (2.20.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: numpy in /usr/local/lib/python3.13/dist-packages (2.1.3)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.13/dist-packages (1.6.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.13/dist-packages (1.5.3)
Requirement already satisfied: absl-py>=1.0.0 in /usr/local/lib/python3.13/dist-packages (from tensorflow) (1.4.0)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/lib/python3.13/dist-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in /usr/local/lib/python3.13/dist-packages (from tensorflow) (25.12.19)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in /usr/local/lib/python3.13/dist-packages (from tensorflow) (0.7.0)
Requirement already satisfied: google_pasta>=0.1.1 in /usr/local/lib/python3.13/dist-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in /usr/local/lib/python3.13/dist-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt_einsum>=2.3.2 in /usr/local/lib/python3.13/dist-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.13/dist-packages (from tensorflow) (26.3)
Requirement already satisfied: protobuf>=5.28.0 in /usr/local/lib/python3.13/dist-packages (from tensorflow) (5.29.6)
Requirement already satisfied: requests<3,>=2.21.0 in /usr/local/lib/python3.13/dist-packages (from tensorflow) (2.32.4)
Requirement already satisfied: setuptools in /usr/local/lib/python3.13/dist-packages (from tensorflow) (75.2.0)
Requirement already satisfied: six>=1.12.0 in /usr/local/lib/python3.13/dist-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/lib/python3.13/dist-packages (from tensorflow) (3.3.0)
Requirement already satisfied: typing_extensions>=3.6.6 in /usr/local/lib/python3.13/dist-packages (from tensorflow) (4.16.0)
Requirement already satisfied: wrapt>=1.11.0 in /usr/local/lib/python3.13/dist-packages (from tensorflow) (2.3.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in /usr/local/lib/python3.13/dist-packages (from tensorflow) (1.83.0)
Requirement already satisfied: tensorboard~=2.20.0 in /usr/local/lib/python3.13/dist-packages (from tensorflow) (2.20.0)
Requirement already satisfied: keras>=3.10.0 in /usr/local/lib/python3.13/dist-packages (from tensorflow) (3.13.2)
Requirement already satisfied: h5py>=3.11.0 in /usr/local/lib/python3.13/dist-packages (from tensorflow) (3.16.0)
Requirement already satisfied: ml_dtypes<1.0.0,>=0.5.1 in /usr/local/lib/python3.13/dist-packages (from tensorflow) (0.6.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.3)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.13/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: wheel<1.0,>=0.23.0 in /usr/local/lib/python3.13/dist-packages (from astunparse>=1.6.0->tensorflow) (0.48.0)
Requirement already satisfied: rich in /usr/local/lib/python3.13/dist-packages (from keras>=3.10.0->tensorflow) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.13/dist-packages (from keras>=3.10.0->tensorflow) (0.1.0)
Requirement already satisfied: optree in /usr/local/lib/python3.13/dist-packages (from keras>=3.10.0->tensorflow) (0.20.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests<3,>=2.21.0->tensorflow) (3.19)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests<3,>=2.21.0->tensorflow) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests<3,>=2.21.0->tensorflow) (2026.7.22)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.13/dist-packages (from tensorboard~=2.20.0->tensorflow) (3.10.3)
Requirement already satisfied: pillow in /usr/local/lib/python3.13/dist-packages (from tensorboard~=2.20.0->tensorflow) (11.3.0)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in /usr/local/lib/python3.13/dist-packages (from tensorboard~=2.20.0->tensorflow) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.13/dist-packages (from tensorboard~=2.20.0->tensorflow) (3.1.8)
Requirement already satisfied: markupsafe>=2.1.1 in /usr/local/lib/python3.13/dist-packages (from werkzeug>=1.0.1->tensorboard~=2.20.0->tensorflow) (3.0.3)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.13/dist-packages (from rich->keras>=3.10.0->tensorflow) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.13/dist-packages (from rich->keras>=3.10.0->tensorflow) (2.21.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.13/dist-packages (from markdown-it-py>=2.2.0->rich->keras>=3.10.0->tensorflow) (0.1.2)

In [ ]:
import pandas as pd
import numpy as np
import joblib
import tensorflow as tf

from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout

print("TensorFlow version:", tf.__version__)
print("Libraries imported successfully!")

TensorFlow version: 2.20.0
Libraries imported successfully!

In [ ]:
data = {
    "food": [
        "Apple", "Banana", "Orange", "Rice", "Brown Rice",
        "Oats", "Egg", "Chicken Breast", "Paneer", "Milk",
        "Curd", "Dal", "Chickpeas", "Lentils", "Almonds",
        "Peanuts", "Potato", "Tomato", "Spinach", "Broccoli",
        "Avocado", "Bread", "Roti", "Pasta", "Fish"
    ],

    "category": [
        "Fruit", "Fruit", "Fruit", "Grain", "Grain",
        "Grain", "Protein", "Protein", "Dairy", "Dairy",
        "Dairy", "Protein", "Protein", "Protein", "Nuts",
        "Nuts", "Vegetable", "Vegetable", "Vegetable",
        "Vegetable", "Fruit", "Grain", "Grain", "Grain",
        "Protein"
    ],

    "calories": [
        52, 89, 47, 130, 123, 389, 155, 165, 265, 61,
        61, 116, 164, 116, 579, 567, 77, 18, 23, 34,
        160, 265, 297, 131, 206
    ],

    "protein": [
        0.3, 1.1, 0.9, 2.7, 2.7, 16.9, 13, 31, 18.3, 3.2,
        3.5, 9, 8.9, 9, 21.2, 25.8, 2, 0.9, 2.9, 2.8,
        2, 9, 11, 5, 22
    ],

    "carbs": [
        14, 22.8, 11.8, 28, 25.6, 66.3, 1.1, 0, 6.1, 4.8,
        4.7, 20, 27.4, 20, 21.6, 16.1, 17.5, 3.9, 3.6,
        7, 8.5, 49, 55, 25, 0
    ],

    "fat": [
        0.2, 0.3, 0.1, 0.3, 1, 6.9, 11, 3.6, 20.8, 3.3,
        3.3, 0.4, 2.6, 0.4, 49.9, 49.2, 0.1, 0.2, 0.4,
        0.4, 14.7, 3.2, 4.5, 1.1, 12
    ],

    "fiber": [
        2.4, 2.6, 2.4, 0.4, 1.6, 10.6, 0, 0, 0, 0,
        0, 7.9, 7.6, 7.9, 12.5, 8.5, 2.2, 1.2, 2.2,
        2.6, 6.7, 2.7, 11, 1.8, 0
    ]
}

df = pd.DataFrame(data)

df.head()

         food category  calories  protein  carbs  fat  fiber
0       Apple    Fruit        52      0.3   14.0  0.2    2.4
1      Banana    Fruit        89      1.1   22.8  0.3    2.6
2      Orange    Fruit        47      0.9   11.8  0.1    2.4
3        Rice    Grain       130      2.7   28.0  0.3    0.4
4  Brown Rice    Grain       123      2.7   25.6  1.0    1.6

In [ ]:
df["nutrition_score"] = (
    df["protein"] * 2
    + df["fiber"] * 1.5
    - df["fat"] * 0.3
)

df[[
    "food",
    "protein",
    "fiber",
    "fat",
    "nutrition_score"
]].head(10)

             food  protein  fiber   fat  nutrition_score
0           Apple      0.3    2.4   0.2             4.14
1          Banana      1.1    2.6   0.3             6.01
2          Orange      0.9    2.4   0.1             5.37
3            Rice      2.7    0.4   0.3             5.91
4      Brown Rice      2.7    1.6   1.0             7.50
5            Oats     16.9   10.6   6.9            47.63
6             Egg     13.0    0.0  11.0            22.70
7  Chicken Breast     31.0    0.0   3.6            60.92
8          Paneer     18.3    0.0  20.8            30.36
9            Milk      3.2    0.0   3.3             5.41

In [ ]:
encoder = LabelEncoder()

df["category_encoded"] = encoder.fit_transform(
    df["category"]
)

print(df[["food", "category", "category_encoded"]].head())

         food category  category_encoded
0       Apple    Fruit                 1
1      Banana    Fruit                 1
2      Orange    Fruit                 1
3        Rice    Grain                 2
4  Brown Rice    Grain                 2

In [ ]:
features = [
    "calories",
    "protein",
    "carbs",
    "fat",
    "fiber",
    "category_encoded"
]

X = df[features].values
y = df["nutrition_score"].values

print("Input shape:", X.shape)
print("Output shape:", y.shape)

Input shape: (25, 6)
Output shape: (25,)

In [ ]:
scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

print(X_scaled[:5])

[[-0.80557883 -1.01039236 -0.26061288 -0.55098194 -0.35738937 -0.99615554]
 [-0.5563613  -0.91752542  0.26156229 -0.54353221 -0.30604033 -0.99615554]
 [-0.83925688 -0.94074215 -0.39115667 -0.55843167 -0.35738937 -0.99615554]
 [-0.28020133 -0.73179153  0.57012034 -0.54353221 -0.87087985 -0.38874362]
 [-0.32735059 -0.73179153  0.42770893 -0.49138411 -0.56278557 -0.38874362]]

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X_scaled,
    y,
    test_size=0.2,
    random_state=42
)

print("Training samples:", len(X_train))
print("Testing samples:", len(X_test))

Training samples: 20
Testing samples: 5

In [ ]:
model = Sequential([

    Dense(
        64,
        activation="relu",
        input_shape=(X_train.shape[1],)
    ),

    Dense(
        32,
        activation="relu"
    ),

    Dropout(0.2),

    Dense(
        16,
        activation="relu"
    ),

    Dense(
        1,
        activation="linear"
    )
])

model.summary()

/usr/local/lib/python3.13/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           448 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 16)             │           528 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3,073 (12.00 KB)

 Trainable params: 3,073 (12.00 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.compile(
    optimizer="adam",
    loss="mse",
    metrics=["mae"]
)

print("ANN compiled successfully!")

ANN compiled successfully!

In [ ]:
history = model.fit(
    X_train,
    y_train,
    epochs=100,
    batch_size=8,
    validation_split=0.2,
    verbose=1
)

Epoch 1/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 1s 221ms/step - loss: 884.0112 - mae: 23.1534 - val_loss: 696.5714 - val_mae: 21.1632
Epoch 2/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - loss: 879.2123 - mae: 23.0753 - val_loss: 692.9365 - val_mae: 21.0976
Epoch 3/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 874.5111 - mae: 23.0035 - val_loss: 689.8959 - val_mae: 21.0382
Epoch 4/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 871.7227 - mae: 22.9495 - val_loss: 686.8291 - val_mae: 20.9797
Epoch 5/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - loss: 872.0948 - mae: 22.9284 - val_loss: 683.9136 - val_mae: 20.9229
Epoch 6/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - loss: 865.0057 - mae: 22.8437 - val_loss: 680.8799 - val_mae: 20.8639
Epoch 7/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 862.8633 - mae: 22.7818 - val_loss: 677.9251 - val_mae: 20.8060
Epoch 8/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - loss: 861.5546 - mae: 22.7505 - val_loss: 675.3395 - val_mae: 20.7518
Epoch 9/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 856.0995 - mae: 22.6659 - val_loss: 672.4203 - val_mae: 20.6933
Epoch 10/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - loss: 851.9860 - mae: 22.6186 - val_loss: 669.0323 - val_mae: 20.6272
Epoch 11/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - loss: 850.2515 - mae: 22.5746 - val_loss: 665.4258 - val_mae: 20.5568
Epoch 12/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 851.0530 - mae: 22.5453 - val_loss: 661.6468 - val_mae: 20.4870
Epoch 13/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - loss: 847.3683 - mae: 22.4686 - val_loss: 658.1272 - val_mae: 20.4195
Epoch 14/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 841.5535 - mae: 22.4048 - val_loss: 654.3317 - val_mae: 20.3474
Epoch 15/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - loss: 835.3135 - mae: 22.3275 - val_loss: 650.1601 - val_mae: 20.2688
Epoch 16/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - loss: 830.2427 - mae: 22.2136 - val_loss: 645.5800 - val_mae: 20.1834
Epoch 17/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - loss: 829.4242 - mae: 22.1685 - val_loss: 640.6852 - val_mae: 20.0926
Epoch 18/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - loss: 823.8616 - mae: 22.1078 - val_loss: 635.3967 - val_mae: 19.9944
Epoch 19/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 816.8315 - mae: 21.9822 - val_loss: 629.8189 - val_mae: 19.8916
Epoch 20/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 811.0052 - mae: 21.8675 - val_loss: 623.8191 - val_mae: 19.7814
Epoch 21/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - loss: 804.9419 - mae: 21.7467 - val_loss: 617.4146 - val_mae: 19.6631
Epoch 22/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 806.7524 - mae: 21.6856 - val_loss: 610.6710 - val_mae: 19.5388
Epoch 23/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 793.4825 - mae: 21.4877 - val_loss: 603.5604 - val_mae: 19.4063
Epoch 24/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 787.2430 - mae: 21.4281 - val_loss: 595.8129 - val_mae: 19.2623
Epoch 25/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - loss: 777.3368 - mae: 21.2654 - val_loss: 587.8088 - val_mae: 19.1112
Epoch 26/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 768.2799 - mae: 21.1408 - val_loss: 579.2770 - val_mae: 18.9488
Epoch 27/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 767.4017 - mae: 21.0443 - val_loss: 569.9220 - val_mae: 18.7713
Epoch 28/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - loss: 745.7055 - mae: 20.7622 - val_loss: 559.9756 - val_mae: 18.5812
Epoch 29/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 742.8656 - mae: 20.6285 - val_loss: 549.7171 - val_mae: 18.3815
Epoch 30/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step - loss: 729.8683 - mae: 20.4421 - val_loss: 538.6683 - val_mae: 18.1669
Epoch 31/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 719.0859 - mae: 20.2328 - val_loss: 527.1512 - val_mae: 17.9383
Epoch 32/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 700.7266 - mae: 19.9638 - val_loss: 514.8413 - val_mae: 17.6950
Epoch 33/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - loss: 701.7889 - mae: 19.7870 - val_loss: 501.6133 - val_mae: 17.4308
Epoch 34/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 96ms/step - loss: 675.1421 - mae: 19.4614 - val_loss: 488.0303 - val_mae: 17.1588
Epoch 35/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 98ms/step - loss: 675.2742 - mae: 19.4497 - val_loss: 474.2358 - val_mae: 16.8749
Epoch 36/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step - loss: 664.0156 - mae: 19.2530 - val_loss: 459.4023 - val_mae: 16.5688
Epoch 37/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step - loss: 648.6262 - mae: 18.8874 - val_loss: 444.3012 - val_mae: 16.2499
Epoch 38/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step - loss: 611.0848 - mae: 18.3366 - val_loss: 427.9717 - val_mae: 15.9034
Epoch 39/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - loss: 629.3923 - mae: 18.5242 - val_loss: 411.2929 - val_mae: 15.5446
Epoch 40/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step - loss: 571.0611 - mae: 17.6256 - val_loss: 393.5922 - val_mae: 15.1575
Epoch 41/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step - loss: 579.4062 - mae: 17.6601 - val_loss: 375.7216 - val_mae: 14.7559
Epoch 42/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step - loss: 551.5399 - mae: 17.1034 - val_loss: 356.8375 - val_mae: 14.3258
Epoch 43/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step - loss: 514.6163 - mae: 16.5391 - val_loss: 337.3731 - val_mae: 13.8687
Epoch 44/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step - loss: 513.0480 - mae: 16.5303 - val_loss: 317.6499 - val_mae: 13.3932
Epoch 45/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step - loss: 488.8951 - mae: 15.9318 - val_loss: 296.8455 - val_mae: 12.8799
Epoch 46/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step - loss: 500.7898 - mae: 16.1584 - val_loss: 274.8880 - val_mae: 12.3246
Epoch 47/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step - loss: 483.6424 - mae: 15.5630 - val_loss: 253.3902 - val_mae: 11.7562
Epoch 48/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step - loss: 451.9122 - mae: 15.0944 - val_loss: 231.7277 - val_mae: 11.1579
Epoch 49/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 404.9580 - mae: 14.3954 - val_loss: 210.8120 - val_mae: 10.5473
Epoch 50/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 370.3229 - mae: 13.7428 - val_loss: 189.9854 - val_mae: 9.9115
Epoch 51/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 384.2048 - mae: 14.1147 - val_loss: 169.1309 - val_mae: 9.3427
Epoch 52/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 389.3975 - mae: 13.6925 - val_loss: 148.5450 - val_mae: 8.7679
Epoch 53/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 282.8613 - mae: 11.8313 - val_loss: 129.5554 - val_mae: 8.2004
Epoch 54/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 298.1255 - mae: 12.3687 - val_loss: 111.6393 - val_mae: 7.6188
Epoch 55/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 263.9008 - mae: 11.1581 - val_loss: 94.1002 - val_mae: 7.0665
Epoch 56/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 250.0697 - mae: 10.9462 - val_loss: 77.8964 - val_mae: 6.6367
Epoch 57/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - loss: 224.6565 - mae: 11.0296 - val_loss: 62.8229 - val_mae: 6.1759
Epoch 58/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 229.5349 - mae: 10.6807 - val_loss: 49.7884 - val_mae: 5.7143
Epoch 59/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 182.4105 - mae: 9.6281 - val_loss: 38.5580 - val_mae: 5.2359
Epoch 60/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - loss: 164.4438 - mae: 8.4854 - val_loss: 29.0541 - val_mae: 4.7460
Epoch 61/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 161.8976 - mae: 8.8609 - val_loss: 21.6489 - val_mae: 4.2471
Epoch 62/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - loss: 147.0365 - mae: 8.6016 - val_loss: 16.2081 - val_mae: 3.7361
Epoch 63/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 123.4304 - mae: 7.9886 - val_loss: 13.0166 - val_mae: 3.2198
Epoch 64/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - loss: 114.3602 - mae: 7.5482 - val_loss: 11.8358 - val_mae: 3.0548
Epoch 65/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - loss: 116.2361 - mae: 7.4171 - val_loss: 12.4020 - val_mae: 3.4125
Epoch 66/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 81.8620 - mae: 6.4242 - val_loss: 14.4349 - val_mae: 3.7360
Epoch 67/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 94.6541 - mae: 6.9264 - val_loss: 18.0134 - val_mae: 4.0561
Epoch 68/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 91.0661 - mae: 7.0544 - val_loss: 22.3748 - val_mae: 4.3265
Epoch 69/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 52.6288 - mae: 5.6049 - val_loss: 26.8328 - val_mae: 4.5263
Epoch 70/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - loss: 75.6930 - mae: 6.7529 - val_loss: 30.5567 - val_mae: 4.6479
Epoch 71/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 89.8482 - mae: 6.8054 - val_loss: 35.0176 - val_mae: 4.7748
Epoch 72/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - loss: 74.9691 - mae: 6.6794 - val_loss: 38.8032 - val_mae: 4.8450
Epoch 73/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - loss: 43.7438 - mae: 4.9980 - val_loss: 41.1652 - val_mae: 5.0275
Epoch 74/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 60.9477 - mae: 6.1081 - val_loss: 42.8793 - val_mae: 5.2061
Epoch 75/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 45.1014 - mae: 4.9792 - val_loss: 43.6719 - val_mae: 5.3128
Epoch 76/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - loss: 60.3113 - mae: 5.2854 - val_loss: 44.7786 - val_mae: 5.4242
Epoch 77/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - loss: 60.8437 - mae: 6.2098 - val_loss: 44.0326 - val_mae: 5.4314
Epoch 78/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 55.0238 - mae: 5.3002 - val_loss: 40.9406 - val_mae: 5.2776
Epoch 79/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 66.9939 - mae: 5.9042 - val_loss: 37.6239 - val_mae: 5.0939
Epoch 80/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - loss: 77.8940 - mae: 6.0637 - val_loss: 35.0632 - val_mae: 4.9564
Epoch 81/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 47.2736 - mae: 5.3700 - val_loss: 32.0105 - val_mae: 4.7734
Epoch 82/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 58.1467 - mae: 5.6378 - val_loss: 29.2187 - val_mae: 4.6079
Epoch 83/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 29.7531 - mae: 3.5674 - val_loss: 27.0389 - val_mae: 4.4688
Epoch 84/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - loss: 31.1825 - mae: 4.3247 - val_loss: 25.2917 - val_mae: 4.3648
Epoch 85/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 30.9898 - mae: 4.4599 - val_loss: 23.4397 - val_mae: 4.2310
Epoch 86/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - loss: 30.9348 - mae: 3.9780 - val_loss: 21.7096 - val_mae: 4.0881
Epoch 87/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 103ms/step - loss: 38.2874 - mae: 5.2156 - val_loss: 20.5914 - val_mae: 3.9847
Epoch 88/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 57.5914 - mae: 5.1238 - val_loss: 20.0603 - val_mae: 3.9347
Epoch 89/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 38.0736 - mae: 4.5474 - val_loss: 19.9341 - val_mae: 3.9189
Epoch 90/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 36.1979 - mae: 4.6825 - val_loss: 20.2006 - val_mae: 3.9412
Epoch 91/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - loss: 30.2150 - mae: 4.5137 - val_loss: 20.3225 - val_mae: 3.9496
Epoch 92/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step - loss: 33.4703 - mae: 4.2695 - val_loss: 19.5941 - val_mae: 3.8905
Epoch 93/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - loss: 30.2554 - mae: 4.6345 - val_loss: 18.2888 - val_mae: 3.7729
Epoch 94/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - loss: 43.6250 - mae: 4.9355 - val_loss: 16.6827 - val_mae: 3.6169
Epoch 95/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 58.5942 - mae: 5.5489 - val_loss: 14.6926 - val_mae: 3.3974
Epoch 96/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 29.3764 - mae: 4.0350 - val_loss: 13.3063 - val_mae: 3.2383
Epoch 97/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 63.2027 - mae: 5.5402 - val_loss: 12.4386 - val_mae: 3.1326
Epoch 98/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 104ms/step - loss: 40.1493 - mae: 4.8164 - val_loss: 12.2750 - val_mae: 3.1161
Epoch 99/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 25.4127 - mae: 3.8509 - val_loss: 11.5676 - val_mae: 3.0165
Epoch 100/100
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - loss: 32.3793 - mae: 4.3690 - val_loss: 10.6237 - val_mae: 2.8710

In [ ]:
loss, mae = model.evaluate(
    X_test,
    y_test,
    verbose=0
)

print("Test Loss:", loss)
print("Mean Absolute Error:", mae)

Test Loss: 63.14225387573242
Mean Absolute Error: 6.925706386566162

In [ ]:
model.save("nutriscan_ann.keras")

joblib.dump(
    scaler,
    "nutriscan_scaler.pkl"
)

joblib.dump(
    encoder,
    "nutriscan_encoder.pkl"
)

print("NutriScan ANN model saved successfully!")

NutriScan ANN model saved successfully!

In [ ]:
def recommend_foods(top_n=5):

    results = []

    for _, food in df.iterrows():

        category_code = encoder.transform(
            [food["category"]]
        )[0]

        input_data = [[
            food["calories"],
            food["protein"],
            food["carbs"],
            food["fat"],
            food["fiber"],
            category_code
        ]]

        input_scaled = scaler.transform(input_data)

        prediction = model.predict(
            input_scaled,
            verbose=0
        )[0][0]

        results.append({
            "Food": food["food"],
            "Calories": food["calories"],
            "Protein": food["protein"],
            "Carbs": food["carbs"],
            "Fat": food["fat"],
            "Fiber": food["fiber"],
            "ANN Score": round(float(prediction), 2)
        })

    result_df = pd.DataFrame(results)

    result_df = result_df.sort_values(
        by="ANN Score",
        ascending=False
    )

    return result_df.head(top_n)

In [ ]:
recommendations = recommend_foods(5)

recommendations

              Food  Calories  Protein  Carbs   Fat  Fiber  ANN Score
7   Chicken Breast       165     31.0    0.0   3.6    0.0      52.42
15         Peanuts       567     25.8   16.1  49.2    8.5      49.39
14         Almonds       579     21.2   21.6  49.9   12.5      48.97
5             Oats       389     16.9   66.3   6.9   10.6      46.99
24            Fish       206     22.0    0.0  12.0    0.0      40.11

In [ ]:
def analyze_food(food_name):

    result = df[
        df["food"].str.lower() ==
        food_name.lower()
    ]

    if result.empty:

        print("Food not found.")

        print("\nAvailable foods:")
        print(", ".join(df["food"]))

        return

    food = result.iloc[0]

    category_code = encoder.transform(
        [food["category"]]
    )[0]

    input_data = [[
        food["calories"],
        food["protein"],
        food["carbs"],
        food["fat"],
        food["fiber"],
        category_code
    ]]

    input_scaled = scaler.transform(input_data)

    prediction = model.predict(
        input_scaled,
        verbose=0
    )[0][0]

    print("=" * 45)
    print("             NUTRISCAN AI")
    print("=" * 45)

    print("Food:", food["food"])
    print("Category:", food["category"])
    print("Calories:", food["calories"], "kcal")
    print("Protein:", food["protein"], "g")
    print("Carbohydrates:", food["carbs"], "g")
    print("Fat:", food["fat"], "g")
    print("Fiber:", food["fiber"], "g")

    print(
        "ANN Nutrition Score:",
        round(float(prediction), 2)
    )

    print("=" * 45)

In [ ]:
analyze_food("Apple")

=============================================
             NUTRISCAN AI
=============================================
Food: Apple
Category: Fruit
Calories: 52 kcal
Protein: 0.3 g
Carbohydrates: 14.0 g
Fat: 0.2 g
Fiber: 2.4 g
ANN Nutrition Score: 4.83
=============================================

In [ ]:
analyze_food("Egg")

=============================================
             NUTRISCAN AI
=============================================
Food: Egg
Category: Protein
Calories: 155 kcal
Protein: 13.0 g
Carbohydrates: 1.1 g
Fat: 11.0 g
Fiber: 0.0 g
ANN Nutrition Score: 25.83
=============================================

In [ ]:
analyze_food("Milk")

=============================================
             NUTRISCAN AI
=============================================
Food: Milk
Category: Dairy
Calories: 61 kcal
Protein: 3.2 g
Carbohydrates: 4.8 g
Fat: 3.3 g
Fiber: 0.0 g
ANN Nutrition Score: 6.5
=============================================

In [ ]:
analyze_food("Bread")

=============================================
             NUTRISCAN AI
=============================================
Food: Bread
Category: Grain
Calories: 265 kcal
Protein: 9.0 g
Carbohydrates: 49.0 g
Fat: 3.2 g
Fiber: 2.7 g
ANN Nutrition Score: 21.9
=============================================

In [ ]:
def calculate_bmi(weight, height):

    height_m = height / 100

    bmi = weight / (height_m ** 2)

    return round(bmi, 2)

In [ ]:
def calculate_calories(
    age,
    weight,
    height,
    gender,
    activity
):

    if gender.lower() == "male":

        bmr = (
            10 * weight
            + 6.25 * height
            - 5 * age
            + 5
        )

    else:

        bmr = (
            10 * weight
            + 6.25 * height
            - 5 * age
            - 161
        )

    activity_factors = {
        "sedentary": 1.2,
        "light": 1.375,
        "moderate": 1.55,
        "active": 1.725
    }

    factor = activity_factors.get(
        activity.lower(),
        1.2
    )

    return round(bmr * factor)

In [ ]:
age = 58
weight = 70
height = 175
gender = "Female"
activity = "moderate"

bmi = calculate_bmi(weight, height)

calories = calculate_calories(
    age,
    weight,
    height,
    gender,
    activity
)

print("========== NUTRISCAN AI ==========")
print("BMI:", bmi)
print("Estimated Daily Calories:", calories, "kcal/day")
print("===================================")

========== NUTRISCAN AI ==========
BMI: 22.86
Estimated Daily Calories: 2081 kcal/day
===================================